SELECT
    IM1.PORT_CODE AS 港コード,
    PORT.PORT_NAME AS 港名,
    IM1.AMT AS 入国者数,
    IM2.AMT AS 出国者数,
    IM1.AMT - IM2.AMT AS 差分
FROM
    IMMIGRATION AS IM1
    INNER JOIN IMMIGRATION AS IM2 ON IM1.PORT_CODE = IM2.PORT_CODE
    INNER JOIN PORT ON IM1.PORT_CODE = PORT.PORT_CODE
WHERE
    IM1.GROUP_CODE = IM2.GROUP_CODE
    AND IM1.GROUP_CODE = '120'
    AND IM1.KIND_CODE = '110'
    AND IM2.KIND_CODE = '120'
    AND 差分 > 0
ORDER BY
    差分 DESC,
    港コード DESC;
