SELECT
    PT.PF_CODE AS 都道府県コード,
    PF.PF_NAME AS 都道府県名,
    PT.TOTAL_AMT AS 総人口2015年,
    PT_2020.TOTAL_AMT AS 総人口2020年,
    ROUND(
        CAST(PT_2020.TOTAL_AMT AS REAL) / (CAST(PT.TOTAL_AMT AS REAL)) * 100
    ) AS 人口増加率
FROM
    POPU_TRANSITION AS PT
    INNER JOIN PREFECTURE AS PF ON PT.PF_CODE = PF.PF_CODE
    INNER JOIN POPU_TRANSITION AS PT_2020 ON PT.PF_CODE = PT_2020.PF_CODE
    AND PT_2020.SURVEY_YEAR = 2020
WHERE
    PT.SURVEY_YEAR = 2015
    AND PT.TOTAL_AMT <= PT_2020.TOTAL_AMT
ORDER BY
    人口増加率 DESC,
    PT.PF_CODE ASC;
